### ISSUE TITLE
The command apply returns HTTP response error

### ISSUE THREAD

**Issue by tjroamer** [Ontotext-AD/ontorefine-cli#8] opened 2022-02-19 22:03 UTC
I tried to use ontorefine-cli (delivered with GraphDB Free 9.10.0) to apply a json mapping to an OntoRefine project I created with GraphDB GUI, but I got the following error:

`
Failed to apply operations on project: '2387256307426' due to: 'Unexpected response : HTTP/1.1 500 '
`

I then created a java app to do the same by following this guide https://github.com/Ontotext-AD/ontorefine-client , but I got the same error message. 

What could be the cause?

Thanks.

**Comment by tonyKunchev** [comment] 2022-02-21 07:42
Hello @tjroamer,
thank you for trying out the libraries and testing them out.

The case that you are presenting is a strange, so before I can pin the root cause, I'll need a bit more information about it.
1. Can you provide the exact steps that you are doing in order to reproduce the issue.
2. Can you provide a sample of the `JSON` that you are passing on.

Apart from that I can suggest a few workarounds that I know are working, if there is an actual issue:
1. You can extract the `JSON` pragmatically:
  1.1. `ontorefine-cli`: execute `extract` command in order to retrieve the `JSON`, store it in a file and than re-use it as much as you need to.
  1.2. `ontorefine-client`: use `GetOperationsCommand` in order to get the operations that are executed over the given project. Effectively the same thing as the `extract` in the `cli` library.
2. As the actual response that you are getting is from the tool itself, you can check the tests that are written to cover the functionalities. If you are going to do that, I'll suggest to check the structure of the `JSON` that you are providing and the structure that is provided in the tests.

My wild guess is that the tool does not like the JSON that you are providing, but I'll need some more information in order to confirm that.

Additionally, I'll check for any edge cases that we've missed during the implementation or if we've broken something recently with other changes. If I find something, I'll fix it and release a new version of the `ontorefine-client` so that you can use it, until we release the fix in `ontoreifne-cli` and GraphDB.

**Comment by tjroamer** [comment] 2022-02-21 15:13
Hello @tonyKunchev,

thanks for your detailed explanation. Yes, it did help me find the problem. The mistake I made was that I was using the mapping json file (downloaded from OntoRefine GUI) for the `apply` command. The mapping json has a different format than the one obtained from the `extract` command. I changed the operations file to the one got from `extract` and it worked well.

I do have a question: it seems that the operations json contains all saved historical operations I made in the GUI. What is the use case scenario of this command? In fact, I am only interested in the final mapping downloaded from the GUI. For that, the command `rdf` would be enough. I am just curious about it.

Thanks a lot.

**Comment by tonyKunchev** [comment] 2022-02-21 15:51
Hey @tjroamer, 

thanks for the explanation. It looks like a problem that the JSON retrieved from the GUI does not apply properly.
I'll take a deeper look in the both structures of the produced JSON documents and add a fix to both libraries.

As for your question: there is no particular use case for the `extract` command, I've just added it for completeness and I guess for cases like yours, to debug problems related to the mappings.
For the second part of the question: yes, `rdf` should be enough in cases where the mapping is already defined in the UI for the project, which data you are retrieving. The logic will try to extract the mapping, if you don't provide one. So calling `rdf` with only the project identifier should be sufficient for your case.

I'll post a comment and close this issue, when I implement a fix for the described problem.

**Comment by tjroamer** [comment] 2022-02-21 16:05
Just for clarity: I am not sure whether this is a bug. In my case, it was just a usage mistake on my side. What I found out is:

The JSON mapping file downloaded from OntoRefine GUI works fine for the `ontorefine-cli rdf` command, while the JSON file extracted from `ontorefine-cli extract` works fine for the `ontorefine-cli apply` command. They just have to match.

That's fine if you do believe it is a bug. ;-)

Thanks a lot.

**Comment by tonyKunchev** [comment] 2022-08-11 09:37
The problems described here should be resolved with the changes that were added by this #14

**Closed by tonyKunchev** 2022-08-11 09:37 UTC
Labels: bug, question
